#!/usr/bin/env python3
# Generated by MLC Compiler
# Auto-generated machine learning training script

# =====================================
# Model 1: KMeans
# Backend: sklearn
# =====================================

# Dataset Loading
import pandas as pd
from sklearn.model_selection import train_test_split

# Load dataset (assuming CSV format)
dataset = pd.read_csv('/home/madhava/datasets/clustering.csv')
# Separate features and target (assuming last column is target)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model: KMeans (sklearn backend)
# Scikit-learn model
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Initialize model
model = KMeans(n_clusters=3, max_iter=300)

# Training (clustering)
print('🚀 Starting clustering...')
model.fit(X_train)
print('✅ Clustering completed!')

# Evaluation
labels = model.labels_
silhouette = silhouette_score(X_train, labels)
print(f'📊 Silhouette Score: {silhouette:.4f}')
print(f'📊 Inertia: {model.inertia_:.4f}')

# Save model
import joblib
joblib.dump(model, 'model.pkl')
print('💾 Model saved as model.pkl')

