#!/usr/bin/env python3
# Generated by MLC Compiler
# Auto-generated machine learning training script

# =====================================
# Model 1: RandomForestClassifier
# Backend: sklearn
# =====================================

n_estimators = 100
max_depth = 4

# Imports
import pandas as pd
from sklearn.model_selection import train_test_split
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
dataset = pd.read_csv('/home/madhava/datasets/classification.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model: RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, max_depth=4)

print('🚀 Starting training...')
model.fit(X_train, y_train)
print('✅ Training completed!')

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'📊 Accuracy: {accuracy:.4f}')
print('\n📋 Classification Report:')
print(classification_report(y_test, y_pred))

# Save model
joblib.dump(model, 'model.pkl')
print('💾 Model saved as model.pkl')
